"""empty message

Revision ID: 5489830e0d2e
Revises: 3006b708ea74
Create Date: 2023-02-24 19:06:06.209279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5489830e0d2e'
down_revision = '3006b708ea74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.alter_column('isbn',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=150),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.alter_column('isbn',
               existing_type=sa.String(length=150),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
